"""
PDF Generator
─────────────
Produces a styled PDF from a structured research report.
Handles markdown ## headers, **bold**, bullet points, and numbered lists.
Adds a title page header and a timestamp footer.
"""

from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from io import BytesIO
from datetime import datetime
import re


# ── Styles ────────────────────────────────────────────────────────────────────

def _build_styles():
    base = getSampleStyleSheet()

    styles = {
        "title": ParagraphStyle(
            "ReportTitle",
            parent=base["Title"],
            fontSize=20,
            textColor=colors.HexColor("#1a1a2e"),
            spaceAfter=6,
        ),
        "subtitle": ParagraphStyle(
            "Subtitle",
            parent=base["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#666680"),
            spaceAfter=16,
        ),
        "h2": ParagraphStyle(
            "H2",
            parent=base["Heading2"],
            fontSize=13,
            textColor=colors.HexColor("#16213e"),
            spaceBefore=14,
            spaceAfter=4,
            borderPad=2,
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontSize=10,
            leading=15,
            textColor=colors.HexColor("#2c2c3e"),
            spaceAfter=5,
        ),
        "bullet": ParagraphStyle(
            "Bullet",
            parent=base["Normal"],
            fontSize=10,
            leading=14,
            leftIndent=16,
            textColor=colors.HexColor("#2c2c3e"),
            spaceAfter=3,
        ),
    }
    return styles


# ── Text Cleaning ─────────────────────────────────────────────────────────────

def _clean_inline(text: str) -> str:
    """Convert **bold** and basic markdown inline to ReportLab XML."""
    # Bold
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    # Italic
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    # Strip remaining markdown artifacts
    text = text.replace("|", "&#124;")
    text = re.sub(r'<(?!b>|/b>|i>|/i>|br/>).*?>', '', text)
    return text.strip()


# ── Page Footer ───────────────────────────────────────────────────────────────

def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#999999"))
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    canvas.drawString(20 * mm, 10 * mm, f"InsightHub Research Report  •  Generated {ts}")
    canvas.drawRightString(
        A4[0] - 20 * mm, 10 * mm, f"Page {doc.page}"
    )
    canvas.restoreState()


# ── Main Generator ─────────────────────────────────────────────────────────────

def generate_pdf(text: str, report_title: str = "InsightHub Research Report", query: str = None) -> BytesIO:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=25 * mm,
        bottomMargin=25 * mm,
    )

    styles = _build_styles()
    content = []

    # ── Title block
    content.append(Paragraph(report_title, styles["title"]))
    if query:
        content.append(Paragraph(f"Follow-up Query: {query}", styles["subtitle"]))
    ts = datetime.now().strftime("%B %d, %Y")
    content.append(Paragraph(f"Generated by InsightHub  •  {ts}", styles["subtitle"]))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#ccccdd")))
    content.append(Spacer(1, 10))

    # ── Parse lines
    for line in text.split("\n"):
        stripped = line.strip()
        if not stripped:
            content.append(Spacer(1, 4))
            continue

        if stripped.startswith("## "):
            heading = stripped[3:].strip()
            content.append(Spacer(1, 6))
            content.append(Paragraph(_clean_inline(heading), styles["h2"]))
            content.append(HRFlowable(
                width="100%", thickness=0.5, color=colors.HexColor("#e0e0ee")
            ))

        elif stripped.startswith("# "):
            heading = stripped[2:].strip()
            content.append(Spacer(1, 8))
            content.append(Paragraph(_clean_inline(heading), styles["h2"]))

        elif re.match(r'^[-•*]\s+', stripped):
            bullet_text = re.sub(r'^[-•*]\s+', '', stripped)
            content.append(Paragraph(f"• {_clean_inline(bullet_text)}", styles["bullet"]))

        elif re.match(r'^\d+\.\s+', stripped):
            content.append(Paragraph(_clean_inline(stripped), styles["bullet"]))

        else:
            content.append(Paragraph(_clean_inline(stripped), styles["body"]))

    doc.build(content, onFirstPage=_footer, onLaterPages=_footer)
    buffer.seek(0)
    return buffer